#server config
  server:
    port: 8008

#datasource config
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://59.7.165.209:3306/sys
      username: root
      password: root
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@oracle.team-greedy.com:1521:xe
#      username: C##SPRING
#      password: SPRING
      hikari:
        auto-commit: false

#jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

#Live Reload 기능 활성화
  devtools:
    livereload:
      enabled: true

  web:
    resources:
      static-locations: file:src/main/resources/static/

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/